version: "3.2"

services:
  tf-serving:
    image: tensorflow/serving:latest-gpu
    container_name: tf-serving
    restart: on-failure
    volumes:
      - ./models/lp:/models/lp
    expose:
      - "8501"
    ports:
      - 8501:8501
    environment:
      - MODEL_NAME=lp